p = input('digite alguma coisa:')
print('O tipo primitivo desse valor é:',type(p))
print('Só tem espaços?',p.isspace())
print('É um numero?',p.isnumeric())
print('É alfabetico?',p.isalpha())
print('É alfa numerico?',p.isalnum())
print('Está em maiusculas?',p.isupper())
print('Está em minusculas?',p.islower())
print('Está capitalizada?',p.istitle())
